repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: '1.0.0'
    hooks:
      - id: sync_with_poetry
        args: ["--db", "pre-commit-sync.json"]
  - repo: https://github.com/python-poetry/poetry
    rev: '2.0.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.4.10'
    hooks:
      # Run the linter.
      - id: ruff
        entry: poetry run ruff check
        language: system
      # Run the formatter.
      - id: ruff-format
        entry: poetry run ruff format
        language: system
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
      - id: mypy
        entry: poetry run mypy
        language: system
        args: []
  - repo: https://github.com/jorisroovers/gitlint
    rev: 'v0.19.1'
    hooks:
      - id: gitlint
